### PR TITLE
Update pipeline tools package (CI)

### PR DESCRIPTION
**Pull request by v-stickykeys**
### Summary

Fixes for dagger

### Motivation

It broke 🤷 

### Changes

- Pin localstack to version `1.2.0`
- Use git commit for dagger project version
- Optimize Dockerfile mutli-stage build

### CODE REVIEW

**Comment by smrz2001** [comment]
Sorry, the current way the versioning works is a little hacky. I did a little experimentation and you can eliminate the extra workflow - updating the version within the context of a runner won't publish that version.

For other repos, we should just remove the tools version suffix entirely - Dagger will automatically pick up the latest git tag (0.2.1 in this case). If we want to pin it to `develop`, that's also fine for now, though probably best to publish stable tags since `develop` can sometimes be broken during testing/iteration.

**Review by smrz2001 — APPROVED** [review]
Latest updates are tested and working 🚀

**Comment by v-stickykeys** [comment]
> updating the version within the context of a runner won't publish that version.
> 
Interesting. I guess the version doesn't matter but is the `project update` required? It seems so if a new plan is added. I kept getting this error saying the file didn't exist. But maybe the workflow was not the thing that fixed it? (I'm not sure what did then 🤷)

```
Run dagger do push -w "actions:push:\"\":\"05f1ff6d8dc5c928efb5d2fd8fe01f66f740e171\":\"05f1ff6d8dc5\":_" -p cue.mod/pkg/github.com/3box/pipeline-tools/ci/plans/smoke.cue
5:36AM ERROR system | failed to load plan: stat /home/runner/work/ceramic-smoke-tests/ceramic-smoke-tests/cue.mod/pkg/github.com/3box/pipeline-tools/ci/plans/smoke.cue: no such file or directory
```

**Comment by smrz2001** [comment]
> > updating the version within the context of a runner won't publish that version.
> > 
> Interesting. I guess the version doesn't matter but is the `project update` required? It seems so if a new plan is added. I kept getting this error saying the file didn't exist. But maybe the workflow was not the thing that fixed it? (I'm not sure what did then 🤷)
> 
> ```
> Run dagger do push -w "actions:push:\"\":\"05f1ff6d8dc5c928efb5d2fd8fe01f66f740e171\":\"05f1ff6d8dc5\":_" -p cue.mod/pkg/github.com/3box/pipeline-tools/ci/plans/smoke.cue
> 5:36AM ERROR system | failed to load plan: stat /home/runner/work/ceramic-smoke-tests/ceramic-smoke-tests/cue.mod/pkg/github.com/3box/pipeline-tools/ci/plans/smoke.cue: no such file or directory
> ```
> 
> 
> 

Yeah, the update really just _pulls_ the specified (or latest) version to the `cue.mod` folder locally for the purpose of running plans.

You'll still have to run the update when testing locally. Just make sure you push your code first then add the commit hash to the update command.

That's because, in this case, the repo being tested is actually the source of the plans so it gets a little weird. Once you push commit X to Github, then run the update using that hash locally, it will pull your committed code into the cue.mod folder.

Alternatively for testing locally, you can just run the plan directly from the repo using the path of the plan file.

**Pull request merged**
